### ISSUE TITLE
make test had returned bad status, won't install without force

### ISSUE THREAD

**Issue by tahseen** [rjbs/Return-Value#3] opened 2015-04-14 21:49 UTC
I think the test are failing which is causing the install to fail on Ubuntu 14:04.

```
root@deploy:/var/www/bugzilla# perl -MCPAN -e 'install Return::Value'
Reading '/root/.cpan/Metadata'
  Database was generated on Tue, 14 Apr 2015 20:41:02 GMT
Running install for module 'Return::Value'
Running make for R/RJ/RJBS/Return-Value-1.666004.tar.gz
Checksum for /root/.cpan/sources/authors/id/R/RJ/RJBS/Return-Value-1.666004.tar.gz ok

  CPAN.pm: Building R/RJ/RJBS/Return-Value-1.666004.tar.gz

Checking if your kit is complete...
Looks good
Writing Makefile for Return::Value
Writing MYMETA.yml and MYMETA.json
cp lib/Return/Value.pm blib/lib/Return/Value.pm
Manifying blib/man3/Return::Value.3pm
  RJBS/Return-Value-1.666004.tar.gz
  /usr/bin/make -- OK
Running make test
  RJBS/Return-Value-1.666004.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports RJBS/Return-Value-1.666004.tar.gz
Running make install
  make test had returned bad status, won't install without force
root@deploy:/var/www/bugzilla# 
```

**Comment by rjbs** [comment] 2015-07-17 23:04
I'm afraid I can't reproduce this.  The report you provided has no actionable details.  There are also no failure reports in CPAN Testers.

I am closing this, but if you have details, let me know.

**Closed by rjbs** 2015-07-17 23:04 UTC
